
---
title: "Goodreads Dataset Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(readr)
library(flexdashboard)
library(rmarkdown)
library(tidyverse)
library(readr)
library(ggplot2)
library(stringr)
library(magrittr)
library(tibble)
library(MASS)
library(dplyr)
library(plotly)
library(wordcloud)
library(tm)
library(RColorBrewer)
library(wordcloud2)
library(SnowballC)
```

Column {data-width=650}
-----------------------------------------------------------------------
Page 1
===================================== 

### Chart A

```{r}
filePath <- "https://raw.githubusercontent.com/ryanmar814/datavizfinal/master/books_publisher.csv"
text <- readLines(filePath)
docs <- Corpus(VectorSource(text))
toSpace <- content_transformer(function(x, pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, removeWords, c ("books", "publishing", "company")) #set stopwords?
docs <- tm_map(docs, removePunctuation)
#docs <- tm_map(docs, stripWhitespace)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)

set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 5,
          max.words=250, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

```

Column {data-width=350}
-----------------------------------------------------------------------
Page 2
=====================================     

### Chart B


```{r}
urlfile = ("https://raw.githubusercontent.com/ryanmar814/datavizfinal/master/LongestBooks25.csv")
LongestBooks25 <- read_csv(url(urlfile))
ggplot(LongestBooks25, aes(x=num_pages, y=publisher))+
  geom_point(color = "hotpink") +
  labs(title = "Publishers with the Longest Books",
       x = "Number of Pages",
       y = "Publisher Name")

```

rmarkdown::run


